"""Detection signals and confidence scoring (planning.md §1).

Milestone 3 implements Signal 1 (the Groq LLM classifier) and the attribution mapping.
Signal 2 (stylometric heuristics) and combine_signals() arrive in Milestone 4.
"""
import json

from groq import Groq

import config

_client = None


def _get_client():
    """Lazily construct the Groq client so importing this module never requires a key."""
    global _client
    if _client is None:
        _client = Groq(api_key=config.GROQ_API_KEY)
    return _client


def score_to_attribution(p_ai):
    """Map a probability-of-AI score in [0, 1] to an attribution label.

    Uses the asymmetric thresholds from config (planning.md §2).
    """
    if p_ai >= config.AI_THRESHOLD:
        return "likely_ai"
    if p_ai <= config.HUMAN_THRESHOLD:
        return "likely_human"
    return "uncertain"


def llm_signal(text):
    """Signal 1 — ask Groq whether the text reads as human- or AI-written.

    Returns {"p_ai": float in [0, 1], "rationale": str}. p_ai is the model's estimate
    that the text is AI-generated (1 = certainly AI, 0 = certainly human).
    Captures semantic/stylistic coherence holistically. Blind spot: framing and
    lightly edited AI; non-deterministic between calls.
    """
    system_prompt = (
        "You are an AI-content detector for a creative-writing platform. "
        "Assess whether the supplied text was written by a human or generated by an AI tool. "
        "Judge holistically: tone, voice, fluency, hedging, and over-uniform structure. "
        "Respond with ONLY a JSON object of the form "
        '{"p_ai": <number between 0 and 1>, "rationale": "<one short sentence>"}. '
        "p_ai is the probability the text is AI-generated: 1.0 = certainly AI, 0.0 = certainly human."
    )

    response = _get_client().chat.completions.create(
        model=config.GROQ_MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": text},
        ],
        temperature=0,
        response_format={"type": "json_object"},
    )

    raw = response.choices[0].message.content
    data = json.loads(raw)

    # Clamp defensively — the model occasionally returns values slightly out of range.
    p_ai = float(data.get("p_ai", 0.5))
    p_ai = max(0.0, min(1.0, p_ai))
    rationale = str(data.get("rationale", "")).strip()

    return {"p_ai": p_ai, "rationale": rationale}
